### ISSUE TITLE
User Story: Validate URL

### ISSUE THREAD

**Issue by ekrebs5** [hpi-swa-teaching/ProjectBoard#59]
As a user I want to open my GitHub project board in Squello. In Squello 1.2, entering a wrong url (e.g. the repo url instead of the project url) throws a generic error after authentification information was added.
In order to save time, I would like a quick check whether I used a correct url directly after I input an url and a custom error (e.g. "We currently only support GitHub projects", "Please input the url of the project, not of the repository", etc) to undestand and fix the error faster.

**Comment by SaturnHafen** [comment]
Hi!

We now (as of [this](https://github.com/hpi-swa-teaching/ProjectBoard/releases/tag/v1.3)) release) support the board url and the repo url.
Additionally, we added some hints for invalid urls.

For reference our tracking issue: #28  

Do you think there is still something missing regarding the board-selection?

**Comment by ekrebs5** [comment]
I think supporting both repo urls and the board url is nice and worked for me. I also like the new hint.

One little bug:
If my credentials are invalid (e.g. because my token expired), trying to access a board through the repo url will give me the "invalid repo url" prompt. Trying to use a board url will ask me to check my credentials. The board url should probably also prompt the letter (or at least not show the wrong url prompt.

**Comment by SaturnHafen** [comment]
These issues should be fixed now (regarding the credentials).
(We are now requesting the repo and checking which specific error comes back)
