### ISSUE TITLE
Refactoring: an vs. a before classes

### ISSUE THREAD

**Issue by linaScience** [hpi-swa-teaching/ProjectBoard#68]
aSPBLane and all other sounds off so change it to anSPBLane to sound more correct

**Comment by jannikhuschka** [comment]
Bevor Kien fragt: Da muss ein "an" und kein "a" hin da man SPB wie "Ess-Pi-Bi" ausspricht, also der erste Laut der Worts ein e-Laut ist und man dann bei der Aussprache von "a SPB..." ins Stocken kommen würde
