### ISSUE TITLE
User Story: Close cards

### ISSUE THREAD

**Issue by MatthiasCr** [hpi-swa-teaching/ProjectBoard#7]
As a user I want to **close cards** in order to **archive or complete a task**.

Blocked by: #1 #10 

- [ ] Close issue
- [ ] UI: Closed issues
- [ ] Check for Github automation updates

**Comment by Phantonia** [comment]
This needs

- [ ] display if card is note, open issue or closed issue
- [ ] add button to close/reopen issue cards
