### ISSUE TITLE
Error when opening a board that has cards without a linked issue

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa-teaching/ProjectBoard#85]
I have a GitHub project board that contains many cards that are not linked to any GitHub issue:

![image](https://user-images.githubusercontent.com/38782922/178857692-62b6100a-3da1-4052-b550-1f42603c80dd.png)

When I try to open this board in Squello, I get a `MessageNotUnderstood: UndefinedObject>>readStream`:

![image](https://user-images.githubusercontent.com/38782922/178857749-d1f82b89-affe-4ce9-866c-a16463016589.png)

In `SPBCardBuilder>>buildFromRemote:into:`, the JSON object does not contain a `content_url`. Most likely, a nil check and some default values for the card are missing here. :-)

**Comment by SaturnHafen** [comment]
Hey,
you should be able to open the board now, but your notes will not show up. That is (currently) intended as we are only using the issue-cards. The notes were not important to our customer so they will have to wait until the next iteration :)
The corresponding user story for the note-support is #40

**Comment by LinqLover** [comment]
A little bit late response from my side, but thanks for the follow-up! :-)
